Rscript CreateMapsSolar.R April.csv April.tif
Rscript CreateMapsSolar.R August.csv August.tif
Rscript CreateMapsSolar.R December.csv December.tif
Rscript CreateMapsSolar.R February.csv February.tif
Rscript CreateMapsSolar.R January.csv January.tif
Rscript CreateMapsSolar.R July.csv July.tif
Rscript CreateMapsSolar.R June.csv June.tif
Rscript CreateMapsSolar.R March.csv March.tif
Rscript CreateMapsSolar.R May.csv May.tif
Rscript CreateMapsSolar.R November.csv November.tif
Rscript CreateMapsSolar.R October.csv October.tif
Rscript CreateMapsSolar.R September.csv September.tif
